name: Test
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Synlig and OSS CAD Suite
        run: |
          curl -sSL https://raw.githubusercontent.com/sifferman/hdl-tool-installer/main/install | bash -s -- tools --oss-cad-suite --synlig
          echo "$GITHUB_WORKSPACE/tools/oss-cad-suite/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/tools/synlig/bin" >> $GITHUB_PATH
      - run: make sim
      - run: make gls
